mode: deployment

fullnameOverride: otel-collector-ksm

image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.112.0   # Latest stable at the time of writing; you can check GitHub for newer

config:
  receivers:
    prometheus:
      config:
        scrape_configs:
          - job_name: 'kube-state-metrics'
            static_configs:
              - targets: ['kube-state-metrics.monitoring.svc.cluster.local:8080']
  processors:
    batch: {}
  exporters:
    otlp:
      endpoint: "signoz-otel-collector.signoz.svc.cluster.local:4317"
      tls:
        insecure: true
  service:
    pipelines:
      metrics:
        receivers: [prometheus]
        processors: [batch]
        exporters: [otlp]
